# scripts/generate_test_cases.py
"""
This script parses the requirements and expected_structure JSON files generated by the generate_requirements.py script, 
then generates a structured JSON file with test case details.
Arguments:
    --inputR / -i   : Path to the input requirements JSON file.
    --inputS / -s   : Path to the input structure JSON file.
    --output / -o  : Path to the output JSON file where test cases will be saved.
Functionality:
    - Reads the input requirements and structure JSON files.
    - Generates test cases based on the requirements and their structure.
    - Outputs a JSON file containing a list of test case objects, each with relevant details.
Note:
    
"""
import json
import argparse

# ---------- Arguments ----------
parser = argparse.ArgumentParser(description="Generate test cases from requirements JSON")
parser.add_argument("--inputR", "-i", required=True, help="Input requirements JSON file")
parser.add_argument("--inputS", "-s", required=True, help="Input structure JSON file")
parser.add_argument("--output", "-o", required=True, help="Output JSON file for test cases")
args = parser.parse_args()

INPUT_REQUIREMENTS_JSON = args.inputR
INPUT_STRUCTURE_JSON = args.inputS
OUTPUT_TEST_CASES_JSON = args.output

# ---------- Read Files ----------
with open(INPUT_REQUIREMENTS_JSON, "r") as f:
    requirements = json.load(f)
with open(INPUT_STRUCTURE_JSON, "r") as f:
    structure_map = json.load(f)

test_cases = []
ti = 1  # Test case ID counter

for es in structure_map: # es is key in structure map, e.g., "REQ-117.130-001"
    for req_id in structure_map[es]: # req_id is the char that completes the requirement id, e.g., "A" for "REQ-117.130-001-A"
        # Find the requirement details from the requirements list
        req_details = next((req for req in requirements if req["requirement_id"] == es + req_id), None)
        if req_details:
            test_case = {
                "test_case_id": f"TC-{ti:03d}",
                "requirement_id": es + req_id,
                "description": f"Test case for {req_details['description']}"
            }
            test_cases.append(test_case)
            ti += 1


# ---------- Output Test Cases JSON ----------
with open(OUTPUT_TEST_CASES_JSON, "w") as f:
    json.dump(test_cases, f, indent=4)
